version: "3.9"

services:
  db:
    image: postgres:16
    container_name: something_new_db
    environment:
      POSTGRES_DB: something_new
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d something_new"]
      interval: 5s
      timeout: 3s
      retries: 20
  redis:
    image: redis:7
    container_name: something_new_redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  postgres_data:


