"""Add user activity and favorites tracking

Revision ID: 29941213f5e3
Revises: 0008
Create Date: 2025-09-17 21:33:56.404277+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29941213f5e3'
down_revision = '0008'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_activities',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('challenge_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_activities_activity_type'), 'user_activities', ['activity_type'], unique=False)
    op.create_index(op.f('ix_user_activities_challenge_id'), 'user_activities', ['challenge_id'], unique=False)
    op.create_index(op.f('ix_user_activities_user_id'), 'user_activities', ['user_id'], unique=False)
    op.create_table('user_favorites',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('challenge_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_favorites_challenge_id'), 'user_favorites', ['challenge_id'], unique=False)
    op.create_index(op.f('ix_user_favorites_user_id'), 'user_favorites', ['user_id'], unique=False)
    op.alter_column('auth_codes', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('auth_codes', 'code',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.drop_constraint(op.f('categories_name_key'), 'categories', type_='unique')
    op.alter_column('challenge_completions', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('challenge_completions', 'challenge_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_index(op.f('ix_cc_challenge_id'), table_name='challenge_completions')
    op.drop_index(op.f('ix_cc_user_id'), table_name='challenge_completions')
    op.drop_index(op.f('ix_challenges_title'), table_name='challenges')
    op.create_index(op.f('ix_challenges_title'), 'challenges', ['title'], unique=True)
    op.alter_column('replacements', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_constraint(op.f('sizes_name_key'), 'sizes', type_='unique')
    op.drop_constraint(op.f('tags_name_key'), 'tags', type_='unique')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('tags_name_key'), 'tags', ['name'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('sizes_name_key'), 'sizes', ['name'], postgresql_nulls_not_distinct=False)
    op.alter_column('replacements', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_index(op.f('ix_challenges_title'), table_name='challenges')
    op.create_index(op.f('ix_challenges_title'), 'challenges', ['title'], unique=False)
    op.create_index(op.f('ix_cc_user_id'), 'challenge_completions', ['user_id'], unique=False)
    op.create_index(op.f('ix_cc_challenge_id'), 'challenge_completions', ['challenge_id'], unique=False)
    op.alter_column('challenge_completions', 'challenge_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('challenge_completions', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.create_unique_constraint(op.f('categories_name_key'), 'categories', ['name'], postgresql_nulls_not_distinct=False)
    op.alter_column('auth_codes', 'code',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('auth_codes', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_index(op.f('ix_user_favorites_user_id'), table_name='user_favorites')
    op.drop_index(op.f('ix_user_favorites_challenge_id'), table_name='user_favorites')
    op.drop_table('user_favorites')
    op.drop_index(op.f('ix_user_activities_user_id'), table_name='user_activities')
    op.drop_index(op.f('ix_user_activities_challenge_id'), table_name='user_activities')
    op.drop_index(op.f('ix_user_activities_activity_type'), table_name='user_activities')
    op.drop_table('user_activities')
    # ### end Alembic commands ###
