name: API CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      - name: Prepare env file
        run: |
          make prepare-env
          if [ -n "${{ secrets.APP_DATABASE_URL }}" ]; then echo "APP_DATABASE_URL=${{ secrets.APP_DATABASE_URL }}" >> .env; fi
      - name: Run tests
        run: make test
